name: AVEL Tests
run-name: ${{ github.actor }} is running AVEL's tests
on:
  push:
    paths:
      - 'tests/**'
      - 'include/**'
      - '.github/workflows/**'
      - 'run_avel_tests.py'
      - 'CMakeLists.txt'
jobs:
  AVEL-x86-tests-GCC-14:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure g++14 is Installed
        run: sudo apt-get install g++-14 -y
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Intel SDE
        run: wget https://downloadmirror.intel.com/843185/sde-external-9.48.0-2024-11-25-lin.tar.xz &&
             tar -xf sde-external-9.48.0-2024-11-25-lin.tar.xz
      - name: Run AVEL test script
        run: python3 run_avel_tests.py -A"x86" -C"/usr/bin/g++-14" -L"./sde-external-9.48.0-2024-11-25-lin/sde64 -icl -- <exec>"
  AVEL-x86-tests-Clang-19:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure clang++-19 is Installed
        run: sudo apt-get install clang++-19 -y
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Intel SDE
        run: wget https://downloadmirror.intel.com/843185/sde-external-9.48.0-2024-11-25-lin.tar.xz &&
             tar -xf sde-external-9.48.0-2024-11-25-lin.tar.xz
      - name: Run AVEL test script
        run: python3 run_avel_tests.py -A"x86" -C"/usr/bin/clang++-19" -L"./sde-external-9.48.0-2024-11-25-lin/sde64 -future -- <exec>"

#  AVEL-ARM-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Not yet implemented"
